name: chessudoku
description: "Chess and Sudoku"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.2         # 상태 관리를 위한 Provider 패턴 구현

  # 네트워킹
  dio: ^5.7.0             # HTTP 클라이언트
  json_annotation: ^4.9.0  # JSON 직렬화/역직렬화
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.2.1
  firebase_auth: ^4.20.0

  # 로컬 저장소
  shared_preferences: ^2.4.0  # 간단한 key-value 저장
  sqflite: ^2.4.1           # SQLite 데이터베이스
  path_provider: ^2.1.5     # 파일 시스템 접근

  # UI/애니메이션
  google_fonts: ^6.2.1      # 구글 폰트 사용
  flutter_svg: ^2.0.17      # SVG 이미지 처리 (체스 기물 아이콘용)
  lottie: ^3.3.1            # Lottie 애니메이션
  flutter_animate: ^4.5.2   # 간단한 애니메이션 구현

  # 유틸리티
  equatable: ^2.0.7         # 값 비교 지원
  collection: ^1.19.0       # 컬렉션 유틸리티
  intl: ^0.20.2             # 국제화/로컬라이제이션

  # 분석/로깅
  logger: ^2.5.0           # 로깅
  sentry_flutter: ^7.10.0  # 에러 추적 (선택적)

  cupertino_icons: ^1.0.8
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7     # 코드 생성
  json_serializable: ^6.7.1  # JSON 직렬화 코드 생성
  mockito: ^5.4.4          # 테스트용 Mock 객체 생성

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
